function __fish_complete_slurm_list_job_states_squeue
    printf "all\tAll states.\n"
    printf "BOOT_FAIL\tJob terminated due to launch failure, typically due to a hardware failure (e.g. unable to boot the node or block and the job can not be requeued).\n"
    printf "BOOT_FAIL\tJob terminated due to launch failure, typically due to a hardware failure (e.g. unable to boot the node or block and the job can not be requeued).\n"
    printf "CANCELLED\tJob was explicitly cancelled by the user or system administrator.  The job may or may not have been initiated.\n"
    printf "COMPLETED\tJob has terminated all processes on all nodes with an exit code of zero.\n"
    printf "CONFIGURING\tJob has been allocated resources, but are waiting for them to become ready for use (e.g. booting).\n"
    printf "COMPLETING\tJob is in the process of completing. Some processes on some nodes may still be active.\n"
    printf "DEADLINE\tJob terminated on deadline.\n"
    printf "FAILED\tJob terminated with non-zero exit code or other failure condition.\n"
    printf "NODE_FAIL\tJob terminated due to failure of one or more allocated nodes.\n"
    printf "OUT_OF_MEMOR\tJob	experienced out of memory error.\n"
    printf "PENDING\tJob is awaiting resource allocation.\n"
    printf "PREEMPTED\tJob terminated due to preemption.\n"
    printf "RUNNING\tJob currently has an allocation.\n"
    printf "RESV_DEL_HOLD\tJob is held.\n"
    printf "REQUEUE_FED\tJob is being requeued by a federation.\n"
    printf "REQUEUE_HOLD\tHeld job is being requeued.\n"
    printf "REQUEUED\tCompleting job is being requeued.\n"
    printf "RESIZING\tJob is about to change size.\n"
    printf "REVOKED\tSibling was removed from cluster due to other cluster starting the job.\n"
    printf "SIGNALING\tJob is being signaled.\n"
    printf "SPECIAL_EXIT\tThe job was requeued in a special state. This state can be set by users, typically in EpilogSlurmctld, if the job has terminated with a particular exit value.\n"
    printf "STAGE_OUT\tJob is staging out files.\n"
    printf "STOPPED\tJob has an allocation, but execution has been stopped with SIGSTOP signal.  CPUS have been retained by this job.\n"
    printf "SUSPENDED\tJob has an allocation, but execution has been suspended and CPUs have been released for other jobs.\n"
    printf "TIMEOUT\tJob terminated upon reaching its time limit.\n"
end

# squeue (SLURM)
complete -c squeue --erase
__fish_complete_slurm_common squeue
complete -c squeue --no-files
complete -c squeue -s a -l all -d "display jobs in hidden partitions"
complete -c squeue -l array-unique -d "display one unique pending job array element per line"
complete -c squeue -l federation -d "Report federated information if a member of one"
complete -c squeue -s h -l noheader -d "no headers on output"
complete -c squeue -l hide -d "do not display jobs in hidden partitions"
complete -c squeue -s i -l iterate -d "specify an interation period"
complete -c squeue -s j -l job -d "comma separated list of jobs IDs to view, default is all" -x -a "(__fish_complete_slurm_comma_separated job_ids)"
complete -c squeue -l local -d "Report information only about jobs on the local cluster"
complete -c squeue -s l -l long -d "long report"
complete -c squeue -s L -l licenses -d "comma separated list of license names to view"
complete -c squeue -s M -l clusters -d "cluster to issue commands to"
complete -c squeue -l noconvert -d "don't convert units from their original type"
complete -c squeue -s o -l format -d "format specification"
complete -c squeue -s O -l Format -d "format specification"
complete -c squeue -s p -l partition -d "comma separated list of partitions to view, default is all partitions"
complete -c squeue -s r -l array -d "display one job array element per line"
complete -c squeue -l sibling -d "Report information about all sibling jobs on a federated cluster"
complete -c squeue -s s -l step -d "comma separated list of job steps to view, default is all"
complete -c squeue -s S -l sort -d "comma separated list of fields to sort on"
complete -c squeue -l start -d "print expected start times of pending jobs"
complete -c squeue -s t -l states -d "comma separated list of states to view" -x -a "(__fish_complete_slurm_list_job_states_squeue)"
